"""Load the original OpenAI GPT-1 (2018) checkpoint into a Hugging Face OpenAIGPTLMHeadModel.

The original release (github.com/openai/finetune-transformer-lm) ships the weights as ten
flat NumPy shards plus a shapes file. This module rebuilds them without needing the old
`parameters_names.json` file, by walking the parameter order of the original TF graph:

    [0] positional embeddings (512, 768)
    [1] token embeddings      (40478, 768)
    then, for each of the 12 blocks, in order:
        attn/c_attn/w, attn/c_attn/b, attn/c_proj/w, attn/c_proj/b,
        ln_1/g, ln_1/b,
        mlp/c_fc/w, mlp/c_fc/b, mlp/c_proj/w, mlp/c_proj/b,
        ln_2/g, ln_2/b

Usage:
    from load_gpt1 import load_gpt1
    model, tok = load_gpt1("/path/to/finetune-transformer-lm/model")
"""
import json
import os

import numpy as np
import torch
from transformers import OpenAIGPTConfig, OpenAIGPTLMHeadModel

try:
    from gpt1_tokenizer import GPT1Tokenizer
except ImportError:  # imported as a package
    from .gpt1_tokenizer import GPT1Tokenizer

BLOCK_PARAM_ORDER = [
    ("attn.c_attn", "weight"), ("attn.c_attn", "bias"),
    ("attn.c_proj", "weight"), ("attn.c_proj", "bias"),
    ("ln_1", "weight"), ("ln_1", "bias"),
    ("mlp.c_fc", "weight"), ("mlp.c_fc", "bias"),
    ("mlp.c_proj", "weight"), ("mlp.c_proj", "bias"),
    ("ln_2", "weight"), ("ln_2", "bias"),
]


def read_original_params(model_dir):
    shapes = json.load(open(os.path.join(model_dir, "params_shapes.json")))
    offsets = np.cumsum([int(np.prod(s)) for s in shapes])
    flat = np.concatenate([np.load(os.path.join(model_dir, f"params_{n}.npy")) for n in range(10)], 0)
    parts = np.split(flat, offsets)[:-1]
    return [p.reshape(s).squeeze() for p, s in zip(parts, shapes)]


def build_state_dict(params):
    sd = {}
    sd["transformer.positions_embed.weight"] = torch.from_numpy(params[0])
    sd["transformer.tokens_embed.weight"] = torch.from_numpy(params[1])
    rest = params[2:]
    n_layer = len(rest) // len(BLOCK_PARAM_ORDER)
    assert n_layer * len(BLOCK_PARAM_ORDER) == len(rest), "unexpected number of parameters"
    i = 0
    for layer in range(n_layer):
        for mod, kind in BLOCK_PARAM_ORDER:
            sd[f"transformer.h.{layer}.{mod}.{kind}"] = torch.from_numpy(np.ascontiguousarray(rest[i]))
            i += 1
    return sd


def load_gpt1(model_dir, device="cpu"):
    params = read_original_params(model_dir)
    cfg = OpenAIGPTConfig(vocab_size=params[1].shape[0], n_positions=params[0].shape[0],
                          n_embd=params[1].shape[1], n_layer=(len(params) - 2) // 12, n_head=12)
    model = OpenAIGPTLMHeadModel(cfg)
    sd = build_state_dict(params)
    missing, unexpected = model.load_state_dict(sd, strict=False)
    # lm_head is tied to the token embeddings; attention bias buffer is generated by the model.
    missing = [m for m in missing if not m.endswith("attn.bias") and m != "lm_head.weight"]
    assert not missing and not unexpected, (missing, unexpected)
    model.tie_weights()
    model.eval().to(device)
    tok = GPT1Tokenizer(os.path.join(model_dir, "encoder_bpe_40000.json"),
                        os.path.join(model_dir, "vocab_40000.bpe"))
    return model, tok


if __name__ == "__main__":
    import sys
    model, tok = load_gpt1(sys.argv[1] if len(sys.argv) > 1 else "/tmp/gpt1/model")
    print(model.config)
    text = "The United States of America is a country in North"
    ids = torch.tensor([tok.encode(text)])
    print(ids.shape, ids[0][:8].tolist())
    with torch.no_grad():
        out = model(ids, labels=ids)
    print("loss", out.loss.item(), "ppl", torch.exp(out.loss).item())
    gen = model.generate(ids, max_new_tokens=20, do_sample=False)
    print(tok.decode(gen[0].tolist()))
